name: 'Custom action'
description: 'For cache dependencies and install dependencies'
inputs:
    path-of-folder:  # id of input
      description: 'path for cache dependencies'
      required: true


runs:
  using: "composite"

  steps:
    - name: Cache NPM Dependencies
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path-of-folder }}
        key: ${{ runner.os }}-${{ inputs.path-of-folder }}-${{hashFiles('package-lock.json')}}
    - name: install dependencies
      run: npm install
      shell: bash