name: Reusable Docker Workflow
on:
  workflow_call: 
    inputs:
      DOCKERHUB_USERNAME:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        description: for docker login
        required: true
      GITHUB_TOKEN:
        description: for ghcr login
        required: true


jobs: 
  reusable-docker:
    
    permissions: 
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        id: login-status
        uses: docker/login-action@v3
        with:
         username: ${{ inputs.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: GHCR LOGIN
        id: ghcr-status
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: login status check
        if: steps.login-status.outcome == 'success'
        run: echo "Login is Successfull"
      - name: checkout rep
        uses: actions/checkout@v4
      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ inputs.DOCKERHUB_USERNAME }}/solar-system:latest
      - name: Testing docker image
        id: docker-test
        run: |
         docker images 
         docker run --name solar-system-app -d \
          -p 3000:3000 \
          -e MONGO_URI=$MONGO_URI \
          -e MONGO_USERNAME=$MONGO_USERNAME \
          -e MONGO_PASSWORD=$MONGO_PASSWORD \
          ${{ inputs.DOCKERHUB_USERNAME }}/solar-system:latest

         echo "Testing image using wget"
         wget -q -O - 127.0.0.1:3000/live | grep live
      - name: Container Registery Push
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: | 
            ${{ inputs.DOCKERHUB_USERNAME }}/solar-system:latest
            ghcr.io/${{github.repository_owner}}/solar-system:latest