name: Workflows implementaion
on:
    workflow_dispatch: 
    push: 
permissions:
    packages: write
env: 

    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
    unit-testing:
       uses: ./.github/workflows/unit-testing-reusable.yml
       with:
        node-version: '["18", "20"]'
        os: '["ubuntu-latest"]'

    coverage:
        name: Code Coverage
        container: 
          image: node:18
        services:
            mongo-db:
              image: siddharth67/mongo-db:non-prod
              options:
                --name mongo
        env: 
            MONGO_URI: 'mongodb://mongo:27017/superData'
            MONGO_USERNAME: non-prod-user
            MONGO_PASSWORD: non-prod-password
        runs-on: ubuntu-latest
        steps:
          - name: checkout rep
            uses: actions/checkout@v4
          # - name: Set up node js environment
          #   uses: actions/setup-node@v4
          - name: Cache NPM Dependencies
            id: cache-npm
            uses: actions/cache@v4
            with:
              path: node_modules
              key: ${{ runner.os }}-node_modules-${{hashFiles('package-lock.json')}}
          - name: install dependencies
            run: npm install
          - name: check code coverage
            continue-on-error: true
            run: npm run coverage
          - name: coverage results
            uses: actions/upload-artifact@v4
            with:
              name: coverage-results
              path: coverage
              retention-days: 3
    report-s3:
      name: upload reports to aws
      needs: [unit-testing, coverage]
      runs-on: ubuntu-latest
      steps:
        - name: download the unit-testing artifact
          uses: actions/download-artifact@v4
          with:
              name: unit-results 

        - name: download the coverage artifact
          uses: actions/download-artifact@v4
          with:
             name: coverage-results

        - name: Merge test files
          run: |
              mkdir reports-${{ github.sha }}/
              mv unit-test-results.xml reports-${{ github.sha }} /
              mv coverage-results.xml reports-${{ github.sha }}/
              ls -ltr reports-${{ github.sha }}/
        - name: Uploading to aws
          run: echo "Uploadingggggg"
    docker:
     
        name: Docker Job Reusable
        needs: [unit-testing, coverage]
        uses: ./.github/workflows/resusable-workflow.yml
        with:
          image-name: solar-system
          docker-context: .
        secrets:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          
    

    dev-deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo  
          uses: actions/checkout@v4
        - name: setup kubectl cli 
          uses: azure/setup-kubectl@v4
          with:
           version: 'v1.26.0' 
        - name: Fetch kubernetes cluster details
          run: |
            kubectl version --short
            echo -------------------------
            kubectl get nodes
            





          