name: Workflows implementaion
on:
    workflow_dispatch: 
    push: 
        branches:
         - main
         - 'feature/*'
env: 

    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
    unit-testing:
        name: Unit testing
        strategy:
            matrix:
                node-version: [18, 19, 20]
                os: [ubuntu-latest, macos-latest]
                exclude:
                    - node-version: 18
                      os: macos-latest 

        runs-on: ${{matrix.os}}
        steps:
        - name: Checkout repository using action
          uses: actions/checkout@v4
        - name: Set up node js env
          uses: actions/setup-node@v4
          with: 
           node-version: ${{matrix.node-version}}
        - name: Cache NPM Dependencies
          id: cache-npm
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ runner.os }}-node_modules-${{hashFiles('package-lock.json')}}
        - name: install dependencies
          run: npm install
        - name: Run test
          id: nodejs-unit-testing-step
          run: npm test
        - name: test results file using artifact
          if: always()
          uses: actions/upload-artifact@v4
          with:
           name: new-test-results
           path: new-test-results.xml

    coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
          - name: checkout rep
            uses: actions/checkout@v4
          - name: Set up node js environment
            uses: actions/setup-node@v4
          - name: Cache NPM Dependencies
            id: cache-npm
            uses: actions/cache@v4
            with:
              path: node_modules
              key: ${{ runner.os }}-node_modules-${{hashFiles('package-lock.json')}}
          - name: install dependencies
            run: npm install
          - name: check code coverage
            continue-on-error: true
            run: npm run coverage
          - name: coverage results
            uses: actions/upload-artifact@v4
            with:
              name: code-coverage-results
              path: coverage
              retention-days: 3
    docker:
        name: For docker login
        needs: [unit-testing, coverage]
        runs-on: ubuntu-latest
        steps:
          - name: Login to Docker Hub
            id: login-status
            uses: docker/login-action@v3
            with:
             username: ${{ vars.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: login status check
            if: steps.login-status.outcome == 'success'
            run: echo "Login is Successful"




          