name: Reusable workflow for unit-testing
on: 
   workflow_call:
      inputs:
        node-version:
          required: true
          type: string
        os:
            required: true
            type: string

        

jobs:
    reusable-unit-testing:
        name: Unit testing
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env: 

         MONGO_URI: 'mongodb://localhost:27017/superData'
         MONGO_USERNAME: non-prod-user 
         MONGO_PASSWORD: non-prod-password
        strategy:
            matrix:
                node-version: ${{ fromJSON(inputs.node-version) }}
                os: ${{ fromJSON(inputs.os) }}
                #exclude:
                    #- node-version: 18
                      #os: macos-latest 

        runs-on: ${{matrix.os}}
        steps:
        - name: Debug inputs
          run: |
              echo "Node Version: ${{ matrix.node-version }}"
              echo "OS: ${{ matrix.os }}"
        - name: for cache and install dependencies
          uses: ./.github/workflows/custom-actions/npm-action
          with:
              npm-path: node_modules
        - name: Run test
          id: nodejs-unit-testing-step
          run: npm test

        - name: Run tests
          run: |
            echo "<test>Passed</test>" > first-test-results.xml
        
        - name: test results file using artifact
          if: always()
          uses: actions/upload-artifact@v4
          with:
           name: first-test-results-${{ matrix.os }}-node${{ matrix.node-version }}
           path: first-test-results.xml